name: Flat

on:
  workflow_dispatch: {}
  push:
    paths:
      - .github/workflows/flat.yml
  schedule:
    - cron: '0 10-13 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.x
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: https://api.nasa.gov/planetary/apod?api_key=DEMO_KEY # The data to fetch every day
          downloaded_filename: nasa-image-of-the-day-metadata.json # The http_url gets saved and renamed in our repository as nasa-image-of-the-day-metadata.json
#          authorization: ${{ secrets.NASA_API_KEY }} # an API key/secret
          postprocess: postprocess.ts # A postprocessing javascript or typescript file written in Deno
