name: Flat

on:
  push:
    paths:
      - .github/workflows/flat.yml # Only run a new workflow every time this file (flat.yaml) file changes
  workflow_dispatch:
  schedule:
    - cron: '0 11 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.x
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: https://api.nasa.gov/planetary/apod?api_key=${{secrets.NASA_API_KEY}} # The data to fetch every day
          downloaded_filename: nasa-image-of-the-day-metadata.json # The http_url gets saved and renamed in our repository as nasa-image-of-the-day-metadata.json
          postprocess: postprocess.ts # A postprocessing javascript or typescript file written in Deno
